transformReq merged
Ankit-Singla/axiosLikeFetch pull request #18
Opened 2021-03-28 06:47 UTC by Aryan-Abhishek

merged the transformReq please review the header part though.

2021-03-28 07:03 UTC, Ankit-Singla requested changes

2021-03-28 07:03 UTC, Ankit-Singla commented on index.js
> +  },
1. Same functionis being used twice, please remove one of them.
2. Request transforms in axios accept data and headers, but they only return data.

2021-03-28 07:03 UTC, Ankit-Singla commented on utils.js
> +    fnList[idx](headers),
You are applying a transform function separately on data and headers. This is not correct.

2021-03-28 07:03 UTC, Ankit-Singla commented on index.js
> +  lastName: "Williams",
Instead of inserting random data, lets try to insert data relevant to project. For example, you can use
```{ name: "axioslikefetch", desc: "Use fetch as if it were a cheaper axios!" }```

2021-03-28 07:03 UTC, Ankit-Singla commented on axiosLikeFetch.js
> -    config = axiosLikeFetch.requestIntercept(config);
This can't be removed from here.

2021-03-28 07:03 UTC, Ankit-Singla commented on axiosLikeFetch.js
> +  },
default transform cannot look like this

2021-03-30 15:45 UTC, Aryan-Abhishek commented
I have updated the code, can you please review it.

2021-03-31 16:45 UTC, Ankit-Singla requested changes

2021-03-31 16:45 UTC, Ankit-Singla commented on .prettierrc.json
> +}
No need to commit this file.

2021-03-31 16:45 UTC, Ankit-Singla commented on axiosLikeFetch.js
> +    data = {...data, descFromDefault: 'Use fetch as it is cheaper axios!'};
This line isn't required. This can be safely removed.
In default transformRequest implementation, you want to check if axios appends some headers, or converts data to certain formats. We can't just append anything to the data.

2021-04-04 13:23 UTC, closed without merging

2021-04-04 13:23 UTC, Aryan-Abhishek commented
will raise a new one